name: Upload Markdown for Indexing
on: [push]
jobs:
  upload-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel PyGithub beautifulsoup4 requests
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        SEARCH_HOST: ${{ secrets.SEARCH_URL }}
        API_USER_PASSWORD: ${{ secrets.API_USER_PASSWORD }}

      run: |
        cd .github/workflows
        python upload_md.py

